version: '3'

services:
  d1819-02:
    build: .
    environment: 
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DBPORT=${DBPORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORT}
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:${PORT}:8080"
    volumes:
      - "logsvol:/usr/src/app/logs"
  mongo:
    image: "mongo"
    environment: 
      - DBPORT=${DBPORT}
    expose:
      - "${DBPORT}"
    command: --logpath /var/log/mongodb/mongodb.log --port ${DBPORT}
    volumes:
      - "dbdata:/data/db"
      - "logsvol:/var/log/mongodb"

volumes:
  logsvol:
  dbdata:

networks: 
  default:
    external:
      name: service-tier